### ISSUE TITLE
Will this work with Squid?

### ISSUE THREAD

**Issue by Uzer1** [wheever/ProxHTTPSProxyMII#10]
Hello. Will this work with Squid to cache https traffic? 
Has anybody tried that?

**Comment by vladns** [comment]
Yes, it works, the code snippet for this:
`...
# Upstream http-proxy.
cache_peer 127.0.0.1 parent 8118 0 no-query no-digest
cache_peer_access 127.0.0.1 deny CONNECT

# Upstream https proxy.
cache_peer 127.0.0.2 parent 8079 0 no-query
cache_peer_access 127.0.0.2 allow CONNECT
...`

**Comment by wmyrda** [comment]
I am struggling with it for several days now to set up just that https://www.prxbx.com/forums/showthread.php?tid=2172&pid=19261#pid19261 Could You post more information how did You achieved it and does you squid work as transparent proxy and use ssl bump not ssl slice? Providing config.ini from ProxHTTPSProxyMII would also be welcomed if any changes to it are required.

PS Software versions You used would also be nice
