### ISSUE TITLE
Support for IPv6

### ISSUE THREAD

**Issue by Null-Kelvin** [wheever/ProxHTTPSProxyMII#9]
Is it planned?

**Comment by vladns** [comment]
So it works the same way, here is the result together with Privoxy:
https://prxbx.com/forums/showthread.php?tid=2228
https://a.radikal.ru/a23/1802/64/d6867f8f7198.png

**Comment by Null-Kelvin** [comment]
I see... it work with IPv6 only if intermediate server works with IPv6. Thanks.
